-- ============================================================
-- PARTNERS CORP · SUPABASE
-- Ejecutar una sola vez desde SQL Editor en el proyecto nuevo.
-- ============================================================

create table if not exists public.talentos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null check (categoria in ('hombres', 'mujeres', 'promotores')),
  precio numeric(10,2) not null default 0 check (precio >= 0),
  especializaciones text[] not null default '{}',
  ciudad text not null default 'Bolivia',
  cobertura text not null default 'Local' check (cobertura in ('Local', 'Nacional')),
  premium boolean not null default false,
  imagen_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists talentos_actualizar_updated_at on public.talentos;
create trigger talentos_actualizar_updated_at
before update on public.talentos
for each row execute function public.actualizar_updated_at();

create index if not exists talentos_categoria_idx on public.talentos (categoria);
create index if not exists talentos_premium_idx on public.talentos (premium);
create index if not exists talentos_created_at_idx on public.talentos (created_at desc);

alter table public.talentos enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.talentos to anon, authenticated;
grant insert, update, delete on table public.talentos to authenticated;
grant usage, select on sequence public.talentos_id_seq to authenticated;

drop policy if exists "Talentos lectura publica" on public.talentos;
drop policy if exists "Talentos insertar autenticado" on public.talentos;
drop policy if exists "Talentos actualizar autenticado" on public.talentos;
drop policy if exists "Talentos eliminar autenticado" on public.talentos;

create policy "Talentos lectura publica"
on public.talentos for select
to anon, authenticated
using (true);

create policy "Talentos insertar autenticado"
on public.talentos for insert
to authenticated
with check (true);

create policy "Talentos actualizar autenticado"
on public.talentos for update
to authenticated
using (true)
with check (true);

create policy "Talentos eliminar autenticado"
on public.talentos for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'talentos',
  'talentos',
  true,
  12582912,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Talentos storage lectura autenticada" on storage.objects;
drop policy if exists "Talentos storage subir" on storage.objects;
drop policy if exists "Talentos storage actualizar" on storage.objects;
drop policy if exists "Talentos storage eliminar" on storage.objects;

create policy "Talentos storage lectura autenticada"
on storage.objects for select
to authenticated
using (bucket_id = 'talentos');

create policy "Talentos storage subir"
on storage.objects for insert
to authenticated
with check (bucket_id = 'talentos');

create policy "Talentos storage actualizar"
on storage.objects for update
to authenticated
using (bucket_id = 'talentos')
with check (bucket_id = 'talentos');

create policy "Talentos storage eliminar"
on storage.objects for delete
to authenticated
using (bucket_id = 'talentos');
